### ISSUE TITLE
m46

### ISSUE THREAD

**Issue by kurtextrem** [cha0sify/chaoschrome#1]
m46 is on the Code Aurora repo I think. Do you plan on adding it? :)

**Comment by cha0sify** [comment]
Yes, i will add m46 as soon as possible

**Comment by cha0sify** [comment]
m46 builds , no modimodifications so far and also it have its own repository you can find it here: https://github.com/ChaOSChriS/chaoschrome_beta
To download apk look here: http://chaosdroid.com/jenkins/job/chrome4sdp-beta/

**Comment by ChaOSChriS** [comment]
m46 builds , no modimodifications so far and also it have its own repository you can find it here: https://github.com/ChaOSChriS/chaoschrome_beta
To download apk look here: http://chaosdroid.com/jenkins/job/chrome4sdp-beta/

**Comment by kurtextrem** [comment]
http://forum.xda-developers.com/general/general/guide-building-chromium-snapdragon-t3255475/post63988006

Posted you there! 
You could put your build on the XDA Labs as well if you feel like it. Or contact the author of the thread, I guess he would do it as well. 

By the way, yesterday the build #2 had some problems... and then today it started building and is building again now. What's up with Jenkins? :D

Cheers! / Danke fürs Builden :)

**Comment by cha0sify** [comment]
Thanks for Posting! :) 

Haha yes, currently i am testing some new things.

Also i am writing all scripts from scratch because the code is hard-coded as jenkins build step. 

I'm working on a template that can build every swe branch and m46 is my 'beta' project :D so i am testing everything there. 

The Job has some Parameters that can build various configs.  Not all are stable yet. 
I will publish all my work soon and if there is enough time i update my Website too.

But the next build i start will be an updated Version :D

**Comment by kurtextrem** [comment]
By the way, some feedback (build #2):
- Sync is turned off
- WebRefiner (adblocker) is turned off
